# Generated by Django 4.0.5 on 2022-06-27 09:40

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(default=product.models.generateUniqueProductId, max_length=35, unique=True)),
                ('productName', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids'), ('mobiles', 'Mobiles'), ('technology', 'Technology'), ('decoration', 'Decoration'), ('kitchen', 'Kitchen')], default='', max_length=25)),
                ('subCategory', models.CharField(blank=True, choices=[('Not Selected', 'Not Selected'), ('upperclothing', 'Upperclothing'), ('bottomclothing', 'Bottomclothing'), ('footwear', 'Footwear'), ('accessories', 'Accessories')], default='Not Selected', max_length=20, null=True)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=300)),
                ('pubishDate', models.DateField()),
                ('productImage', models.ImageField(default='', upload_to='product/images')),
            ],
        ),
    ]
